deploy:
  provider: lambda
  function_name: lambda-test
  region: us-east-1
  role: arn:aws:iam::0123456789012:role/lambda_basic_execution
  runtime: nodejs4.3
  handler_name: handler
  access_key_id: AKIAI3UL2XSC6EWAKKOA
  secret_access_key:
    secure: c4PpzaMlqaTQnwBHz9V0VKHlSQL3O0R/wHsE8pPjfEXdtvwQ26WFpaCWfZXZrVw18bVg9d2mma0VW6SHd/RmzGwRiA7ynY2q0K8tg9t075xhpf2ZKYQ8d96tGcgGm4jl7QCZR9K407enfi154CDejnl9sIhVecjYgLYjZs7nCvA//3phWJ16OaIRxtNt9sq2l7xbA7mBUOG165vjME+3TSRs4ABhf3eK4YYtsuGps/NntRqHNEcpEmtPDr9hqX7PA7vILPS2QguREmBMf74dXvfJpJX26MBQjGItiZNNMIeoWvpIdRQTW9g+A2CZkUEte6UjUMwLWoxxxqZvcWZfZKUraRnHuM18N2t01KQdSM1P899TXaRahQGyvyP1cgt+2+P5smuP7UjQAZflauuo9QckShZTTHecasvMsevZrBUrNhFJYuptfDWTZRKaJpt5/v0/Js3hHmd2Utui8MQPSZwIRDmogdUsbWQcghiTFVCCaz/+kCvj8vP5M4j66gii8E7jIYQ6v1JXOJLhf1xYTML4mQlcrCJ9jj4CYsIk2Tk8AhsVyriwOk3cdDMVtoW3uG0nZajSOwv7sJq6OIEjV1fksZtryvnbKHgskbxGinoKtbm0Wo/NHYq1ndE7FCeEwlnNEh6ajVU9XqNChhmwnMTXO8CNTQmnljxhbTMKMAI=
